site_name: ""
site_description: "Developer-Friendly Reliability Engineering | /lɥœʁ/"
site_author: "Sylvain Hellegouarch"
site_url: https://docs.lueur.dev
repo_url: https://github.com/rebound-how/rebound
repo_name: rebound/lueur
edit_uri: edit/main/docs/lueur/docs
copyright: Copyright &copy; 2024 - 2025 Sylvain Hellegouarch
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sylvainhellegouarch/
      name: Sylvain Hellegouarch on Linkedin
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@lawouach
      name: Sylvain Hellegouarch on Fosstodon
nav:
  - Home: index.md
  - Getting Started:
    - "Install": tutorials/install.md
    - "tl;dr": tutorials/tldr.md
    - "Getting Started": tutorials/getting-started.md
    - "Creating a Reliability Testing Scenario": tutorials/create-scenario.md
  - "How-To Guides":
    - "Install lueur": how-to/install.md
    - "Configure Latency": how-to/proxy/faults/configure-latency.md
    - "Configure Bandwidth": how-to/proxy/faults/configure-bandwidth.md
    - "Configure Packet Loss": how-to/proxy/faults/configure-packet-loss.md
    - "Configure HTTP Error": how-to/proxy/faults/configure-http-error.md
    - "Configure Jitter": how-to/proxy/faults/configure-jitter.md
    - "Run In Stealth Mode": how-to/proxy/stealth/configure-stealth-mode.md
    - "Enable Open Telemetry Observability": how-to/observability/traces.md
    - "Integrate GitHub Actions": how-to/ci/github.md
    - "Run On Kubernetes": how-to/platform/run-on-kubernetes.md
    - "Run With Docker": how-to/platform/run-with-docker.md
  - Reference:
    - "CLI Commands": reference/cli-commands.md
    - "Scenario File Format": reference/scenario-file-format.md
    - "Environment Variables": reference/environment-variables.md
    - "Architecture": reference/architecture-overview.md
  - Explanations:
    - "Why lueur?": explanations/why-lueur.md
    - "Fault Injection Basics": explanations/fault-injection-basics.md
    - "Understanding eBPF": explanations/understanding-ebpf.md
    - "Technical Choices": reference/technical-choices.md
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    annotation: material/plus-circle
    repo: fontawesome/brands/github
  palette:
    scheme: slate
    primary: black
    accent: yellow

  features:
    - navigation.tabs
    - content.tabs
    - search.suggest
    - search.highlight
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    #- content.action.edit

  
extra_css:
  - stylesheets/lueur.css

plugins:
  - search
  - glightbox
  - tags
  - social:
      enabled: !ENV [CI, false]
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: "hooks:copy_install"

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.blocks.definition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
