---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fault-proxy
  labels:
    app: fault-proxy
automountServiceAccountToken: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fault-proxy-config
  labels:
    app: fault-proxy
data:
  FAULT_UPSTREAMS: "http://fault-demo:7070"
  FAULT_WITH_LATENCY: "true"
  FAULT_LATENCY_MEAN: "300"

---
apiVersion: v1
kind: Service
metadata:
  name: fault-proxy
  labels:
    app: fault-proxy
spec:
  selector:
    app: fault-proxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fault-proxy
  labels:
    app: fault-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fault-proxy
  template:
    metadata:
      labels:
        app: fault-proxy
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: fault-proxy
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
        - name: fault-proxy
          image: localhost:32000/rebound/fault:latest
          imagePullPolicy: Always
          tty: true
          args:
            - --log-stdout
            - --log-level
            - debug
            - run
            - --no-ui
            - --proxy-address
            - "0.0.0.0:8080"
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: fault-proxy-config
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL