---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lueur-demo
  labels:
    app: lueur-demo
automountServiceAccountToken: false

---
apiVersion: v1
kind: Service
metadata:
  name: lueur-demo
  labels:
    app: lueur-demo
spec:
  selector:
    app: lueur-demo
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lueur-proxy-stealth
  labels:
    app: lueur-proxy-stealth
automountServiceAccountToken: false

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lueur-proxy-stealth-config
  labels:
    app: lueur-proxy-stealth
data:
  LUEUR_EBPF_PROCESS_NAME: "curl"
  LUEUR_WITH_LATENCY: "true"
  LUEUR_LATENCY_MEAN: "300"

---
apiVersion: v1
kind: Service
metadata:
  name: lueur-proxy-stealth
  labels:
    app: lueur-proxy-stealth
spec:
  selector:
    app: lueur-proxy-stealth
  ports:
    - name: proxy
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: ebpf-proxy
      protocol: TCP
      port: 10520
      targetPort: 10520

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lueur-demo
  labels:
    app: lueur-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lueur-demo
  template:
    metadata:
      labels:
        app: lueur-demo
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: lueur-demo
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
        - name: lueur-demo
          image: localhost:32000/rebound/lueur:latest
          imagePullPolicy: Always
          tty: true
          args:
            - demo
            - run
            - "0.0.0.0"
            - "7070"
          ports:
            - containerPort: 7070
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL

        - name: lueur-proxy
          image: localhost:32000/rebound/lueur-ebpf:latest
          imagePullPolicy: Always
          tty: true
          args:
            - --log-stdout
            - --log-level
            - debug,tower_http=debug
            - run
            - --no-ui
            - --proxy-address
            - "0.0.0.0:8080"
            - --stealth
            - --ebpf-proxy-iface
            - eth0
            - --ebpf-proxy-port
            - "10520"
          ports:
            - containerPort: 8080
              name: proxy
            - containerPort: 10520
              name: ebpf-proxy
          envFrom:
            - configMapRef:
                name: lueur-proxy-stealth-config
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: true
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - BPF
                - NET_ADMIN
          volumeMounts:
          - name: sys-fs-cgroup
            mountPath: /sys/fs/cgroup
          - name: sys-fs-bpf
            mountPath: /sys/fs/bpf
      volumes:
        - name: sys-fs-cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: sys-fs-bpf
          hostPath:
            path: /sys/fs/bpf