FROM --platform=$BUILDPLATFORM gcr.io/distroless/cc-debian12

ARG TARGETARCH
ARG BUILDPLATFORM
ARG CLI_PREFIX_PATH
ARG EBPF_PREFIX_PATH

LABEL org.opencontainers.image.source=https://github.com/rebound-how/rebound
LABEL org.opencontainers.image.description="lueur network proxy CLI with ebpf support"
LABEL org.opencontainers.image.licenses=Apache-2.0

COPY --chown=nonroot:nonroot --chmod=+x ${CLI_PREFIX_PATH}-${TARGETARCH}/lueur /home/nonroot/lueur
COPY --chown=nonroot:nonroot ${EBPF_PREFIX_PATH}-${TARGETARCH} /home/nonroot/.cargo/bin/lueur-ebpf

WORKDIR /home/nonroot
USER nonroot

EXPOSE 8080

ENTRYPOINT ["/home/nonroot/lueur"]
CMD []

