site_name: ""
site_description: "Orchestrate Your Resilience Strategy | Reliably"
site_author: "Sylvain Hellegouarch"
site_url: https://reliably.com
repo_url: https://github.com/rebound-how/rebound
repo_name: rebound/reliably
edit_uri: edit/main/docs/reliably/docs
copyright: Copyright &copy; 2025 Sylvain Hellegouarch
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sylvainhellegouarch/
      name: Sylvain Hellegouarch on Linkedin
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@lawouach
      name: Sylvain Hellegouarch on Fosstodon
nav:
  - Home: index.md
  - Getting Started:
    - "Install": tutorials/install/index.md
    - "Install the Platform": tutorials/install/platform.md
    - "Install the CLI": tutorials/install/cli.md
    - "Quick Tour": tutorials/tour.md
  - "How-To Guides":
    - "Environments": guides/environments.md
    - "Integrations": guides/integrations.md
    - "Runtime Strategies": guides/runtime-strategies.md
    - "Contributions": guides/contributions.md
  - Reference:
    - "Concepts": reference/concepts.md
    - "Glossary": reference/glossary.md
  - Explanations:
    - "Features": explanation/features.md
    - "Relation to Chaos Toolkit": explanation/chaostoolkit.md
    - "About Deployments": explanation/about-deployments.md

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    annotation: material/plus-circle
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: white
    accent: reliably

  features:
    - navigation.tabs
    - content.tabs
    - search.suggest
    - search.highlight
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    #- content.action.edit

  
extra_css:
  - stylesheets/reliably.css

plugins:
  - search
  - glightbox
  - tags
  - social:
      enabled: !ENV [CI, false]
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: true
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: "hooks:copy_install"

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.blocks.definition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
