---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "reliably.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "reliably.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "reliably.serviceAccountName" . }}
  namespace: {{ .Release.namespace }}
roleRef:
  kind: Role
  name: {{ include "reliably.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
