apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reliably.fullname" . }}
  labels:
    {{- include "reliably.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.reliably.database.url | b64enc | quote }}
  CRYPTO_CRYPTOGRAPHY_SECRET_KEY: {{ .Values.reliably.encryption.key | default 32 | randAscii | b64enc | b64enc | quote}}
  SESSION_SECRET_KEY: {{ .Values.reliably.session.key | default 32 | randAscii | sha256sum | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.reliably.assistant.openai_key | b64enc | quote }}
