name: Lueur Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/lueur/**'
      - '.github/workflows/build-lueur-docs.yaml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.12
          cache: true
          cache-dependency-path: |
            ./pdm.lock

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - uses: actions/cache@v4
        with:
          key: lueur-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            lueur-
  
      - name: Install dependendencies
        run: pdm install --no-self
        
      - name: Build and deploy Documentation
        run: pdm run deploy-docs