name: Build Reliably CLI

on:
  push:
    branches:
      - main
    paths: 
      - 'reliably/cli/**'
      - '.github/workflows/build-reliably-cli.yaml'
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - main
    paths: 
      - 'reliably/cli/**'
    tags-ignore:
      - "**"

jobs:
  checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          prerelease: true
          cache-dependency-path: 'reliably/cli/pdm.lock'

      - name: Ensure lock file is up to date
        working-directory: ./reliably/cli
        run: |
          pdm lock --check

      - name: Install dependencies
        working-directory: ./reliably/cli
        run: |
          pdm sync -G dev

      - name: Run Lint
        working-directory: ./reliably/cli
        run: |
          pdm run lint

      - name: Run Tests
        working-directory: ./reliably/cli
        run: |
          pdm run pytest
  