name: Build and Upload Reliably Job Container Image

permissions:
  contents: write

on:
  push:
    branches:
      - release
    paths: 
      - 'deploy/docker/job/**'
      - '.github/workflows/release-reliably-job.yaml'

jobs:
  build-and-upload-docker-reliably-job-images:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/rebound-how/reliably-job
          flavor: |
            latest=true
          tags: |
            type=sha

      - name: Build and push lueur CLI
        uses: docker/build-push-action@v6
        with:
          context: "."
          file: "./deploy/docker/job/Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64
