name: Release Lueur Binaries

permissions:
  contents: write

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
    paths: 
      - 'lueur/**'
      - '.github/workflows/release-lueur-bin.yaml'

jobs:
  promote-the-release:
    needs:
      - release-assets
      - release-ebpf-assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Promote lueur release
        run: |
          gh release edit "$GITHUB_REF_NAME" --latest=true --draft=false
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-assets:
    needs:
      - create-the-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
            artifact_name: lueur
            asset_name: lueur-cli

    name: Build workspace on ${{ matrix.os }} / ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
         rustup target add ${{ matrix.target }}
         rustup toolchain install nightly --component rust-src -t ${{ matrix.target }}
         rustup update nightly
         rustup override set nightly

      - uses: Swatinem/rust-cache@v2
        with:
         prefix-key: lueur
         shared-key: ${{ github.job }}-${{ matrix.target }}
         workspaces: |
           lueur

      - name: Publish lueur CLI
        if: matrix.os == 'ubuntu-24.04' && matrix.target == 'x86_64-unknown-linux-gnu'
        working-directory: ./lueur/lueur-cli
        run: |
          cargo publish --allow-dirty --no-verify --package lueur-cli --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  release-ebpf-assets:
    needs:
      - create-the-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
            artifact_name: lueur

    name: Build workspace on ${{ matrix.os }} / ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
         rustup target add ${{ matrix.target }}
         rustup toolchain install nightly --component rust-src -t ${{ matrix.target }}
         rustup update nightly
         rustup override set nightly

      - uses: Swatinem/rust-cache@v2
        with:
         prefix-key: lueur
         shared-key: ${{ github.job }}-${{ matrix.target }}
         workspaces: |
           lueur

      - name: Publish lueur ebpf-programs
        if: matrix.os == 'ubuntu-24.04' && matrix.target == 'x86_64-unknown-linux-gnu'
        working-directory: ./lueur/lueur-ebpf-programs
        run: |
          cargo publish --allow-dirty --no-verify --package lueur-ebpf-programs --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
