name: Prepare Next Lueur Release

permissions:
  contents: write

on:
  pull_request:
    types: [labeled]

jobs:
  merge-into-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge by labeled
        uses: devmasx/merge-branch@master
        with:
          label_name: 'prepare release'
          target_branch: 'release'
          github_token: ${{ secrets.GITHUB_TOKEN }}
