name: Release Lueur Binaries

permissions:
  contents: write

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
    paths: 
      - 'lueur/**'
      - '.github/workflows/release-lueur-bin.yaml'

jobs:
  create-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-cliff
        uses: taiki-e/install-action@git-cliff

      - name: Generate and save a changelog
        run: |
          git checkout main

          nex_ver=$(git cliff --bumped-version -c lueur/cliff.toml)
          echo $nex_ver
          commit_msg="chore(release): update CHANGELOG.md for ${nex_ver}"

          git-cliff \
            --with-commit "$commit_msg" \
            --strip all \
            -o lueur/CHANGELOG.md \
            -c lueur/cliff.toml \
            --include-path "lueur/**/*" \
            --include-path ".github/workflows/release-lueur-bin.yaml" \
            --exclude-path "reliably/*" \
            --exclude-path "chaostoolkit/*" \
            --bump
    
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add lueur/CHANGELOG.md
          git commit -m "$commit_msg"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main

      - uses: taiki-e/create-gh-release-action@v1
        if: github.repository_owner == 'rebound-how'
        with:
          changelog: ./lueur/CHANGELOG.md
          title: lueur $tag
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true

  upload-assets:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04
            artifact_name: lueur
            asset_name: lueur-linux-aarch64
          - target: aarch64-apple-darwin
            os: macos-latest
            artifact_name: lueur
            asset_name: lueur-macos-aarch64
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
            artifact_name: lueur
            asset_name: lueur-linux-amd64
          - target: x86_64-apple-darwin
            os: macos-latest
            artifact_name: lueur
            asset_name: lueur-macos-amd64
          - target: universal-apple-darwin
            os: macos-latest
            artifact_name: lueur
            asset_name: lueur-macos-universal
          - os: windows-latest
            artifact_name: lueur.exe
            asset_name: lueur-windows-amd64

    name: Build workspace on ${{ matrix.os }} / ${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
         rustup toolchain install nightly --component rust-src
         rustup update nightly
         rustup override set nightly

      - uses: Swatinem/rust-cache@v2
        with:
         key: ${{ matrix.target }}
         workspaces: |
           lueur
      
      - name: Install gRPC build dependencies (Linux)
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get update
          sudo apt install -y protobuf-compiler libssl-dev

      - name: Install bpf-linker
        if: matrix.os == 'ubuntu-24.04'
        run: cargo install bpf-linker --git https://github.com/aya-rs/bpf-linker.git

      - name: Install gRPC build dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install protoc --pre -y

      - name: Install gRPC build dependencies (MacOSX)
        if: matrix.os == 'macos-latest'
        run: |
          brew install protobuf

      - name: Build
        run: cargo build --release --locked
        working-directory: ./lueur/lueur-cli

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          promote: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: lueur/lueur-cli/target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}

      - name: Publish CLI assets to Cargo Registry
        uses: katyo/publish-crates@v2
        with:
          path: './lueur/lueur-cli'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true

      - name: Publish ebpf assets to Cargo Registry
        if: matrix.os == 'ubuntu-24.04'
        uses: katyo/publish-crates@v2
        with:
          path: './lueur/lueur-ebpf-programs'
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          ignore-unpublished-changes: true
